export const data = [
  {
    id: 1,
    name: "Bike 1",
    frameType: ["Full-suspension", "Diamond", "Step-through"],
    frameFinish: ["Matte", "Shiny"],
    wheels: ["Road wheels", "Mountain wheels", "Fat bike wheels"],
    rims: ["Red", "Black", "Blue"],
    chain: ["Single-speed chain", "8-speed chain"],
    stock: true,
  },
  {
    id: 2,
    name: "Bike 2",
    frameType: ["Full-suspension", "Diamond", "Step-through"],
    frameFinish: ["Matte", "Shiny"],
    wheels: ["Road wheels", "Mountain wheels", "Fat bike wheels"],
    rims: ["Red", "Black", "Blue"],
    chain: ["Single-speed chain", "8-speed chain"],
    stock: false,
  },
  {
    id: 3,
    name: "Bike 3",
    frameType: ["Full-suspension", "Diamond", "Step-through"],
    frameFinish: ["Matte", "Shiny"],
    wheels: ["Road wheels", "Mountain wheels", "Fat bike wheels"],
    rims: ["Red", "Black", "Blue"],
    chain: ["Single-speed chain", "8-speed chain"],
    stock: true,
  },
  {
    id: 4,
    name: "Bike 4",
    frameType: ["Full-suspension", "Diamond", "Step-through"],
    frameFinish: ["Matte", "Shiny"],
    wheels: ["Road wheels", "Mountain wheels", "Fat bike wheels"],
    rims: ["Red", "Black", "Blue"],
    chain: ["Single-speed chain", "8-speed chain"],
    stock: true,
  },
];
